import 'server-only'

import { sql } from './sql'

export async function createCollectionsDatabase() {
  const createTableSQL = `
    -- 1. Create the table
    CREATE TABLE IF NOT EXISTS public.collections (
      id bigint generated by default as identity not null,
      created_at timestamp with time zone not null default now(),
      collection_name character varying not null,
      locale character varying not null,
      title character varying not null,
      content jsonb null,
      updated_at timestamp with time zone not null default now(),
      constraint collections_pkey primary key (id),
      constraint collections_title_locale_key unique (title, locale)
    );

    -- 2. Enable Row Level Security (RLS)
    ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

    -- 3. Create a basic RLS Policy (e.g., Public Read Access)
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'collections' AND policyname = 'Enable read access for all users'
      ) THEN
        CREATE POLICY "Enable read access for all users" 
        ON public.collections FOR SELECT USING (true);
      END IF;
    END $$;

    -- 4. Create GIN Index for the JSONB content column
    CREATE INDEX IF NOT EXISTS idx_collections_content_gin 
    ON public.collections USING GIN (content);

    -- 5. Create or Update the trigger function
    CREATE OR REPLACE FUNCTION public.handle_updated_at()
    RETURNS trigger AS $$
    BEGIN
      NEW.updated_at = now();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    -- 6. Attach the auto-update trigger
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at') THEN
        CREATE TRIGGER set_updated_at
        BEFORE UPDATE ON public.collections
        FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
      END IF;
    END $$;
  `

  try {
    await sql.unsafe(createTableSQL)
  } catch (error) {
    console.error('createCollectionsDatabase :: Initialization Error:', error)

    return { success: false, error }
  }

  return {
    success: true,
    message:
      'createCollectionsDatabase :: Table and triggers verified/created.',
  }
}
