import 'server-only'

import { sql } from './sql'

export async function createCmsUsersDatabase() {
  const createTableSQL = `
    -- 1. Create the custom type if it doesn't exist
    DO $$ 
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cms_roles') THEN
            CREATE TYPE public.cms_roles AS ENUM ('admin', 'moderator', 'editor');
        END IF;
    END $$;

    -- 2. Create the table if it doesn't exist
    CREATE TABLE IF NOT EXISTS public.cms_users (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default now(),
        user_id uuid not null,
        role public.cms_roles not null default 'editor'::cms_roles,
        constraint cms_users_pkey primary key (id),
        constraint cms_users_user_id_key unique (user_id),
        constraint cms_users_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
    ) TABLESPACE pg_default;

    -- 3. Enable RLS (Safe to run multiple times)
    ALTER TABLE public.cms_users ENABLE ROW LEVEL SECURITY;

    -- 4. Re-create the policy to ensure it's up to date
    DROP POLICY IF EXISTS "Users can view their own cms roles" ON public.cms_users;

    CREATE POLICY "Users can view their own cms roles" 
    ON public.cms_users 
    FOR SELECT 
    TO authenticated 
    USING (
        auth.uid() = user_id
    );
  `

  try {
    await sql.unsafe(createTableSQL)
  } catch (error) {
    console.error('createCmsUsersDatabase :: Initialization Error:', error)

    return { success: false, error }
  }

  return {
    success: true,
    message: 'createCmsUsersDatabase :: Table and triggers verified/created.',
  }
}
